"""Überträgt eine bestehende Planner-SQLite-Datenbank nach PostgreSQL.

    python -m backend.scripts.migrate_sqlite_to_postgres --source local_data/database/dienstplaene.db --dry-run
    python -m backend.scripts.migrate_sqlite_to_postgres --source local_data/database/dienstplaene.db

Grundsätze (Sprint-Punkte 20-25):

  * Die SQLite-Quelle wird ausschließlich LESEND geöffnet (`mode=ro`, immutable
    URI). Das Skript kann die Ausgangsdaten nicht beschädigen.
  * Das Ziel kommt ausschließlich aus DATABASE_URL - nie aus einem Argument,
    damit keine Zugangsdaten in der Prozessliste oder Shell-History landen.
  * Standardmäßig sicher: ist das Ziel nicht leer, bricht das Skript ab. Erst
    `--allow-non-empty` erlaubt das Überschreiben, und auch dann wird jeder
    gelöschte Datensatz vorher gezählt und gemeldet.
  * Alles läuft in EINER Transaktion. Ein Fehler an irgendeiner Stelle rollt
    den gesamten Lauf zurück - es gibt keinen halb migrierten Zustand.
  * IDs werden explizit übernommen (die IDENTITY-Spalten sind bewusst
    GENERATED BY DEFAULT). Danach werden die Sequenzen auf MAX(id) gesetzt, so
    dass der nächste Insert garantiert darüber liegt.
  * Nach dem Schreiben wird verifiziert: Zeilenzahlen pro Tabelle, fachliche
    Stichproben und referenzielle Integrität - jeweils mit PASS/FAIL.
  * Waisen in den Altdaten werden NIE automatisch gelöscht. Sie werden gemeldet
    und führen zum Abbruch, weil PostgreSQL die Fremdschlüssel jetzt erzwingt.
"""
from __future__ import annotations

import argparse
import logging
import os
import sqlite3
import sys
from dataclasses import dataclass, field
from pathlib import Path

import psycopg
from psycopg import sql as pgsql

from .. import db as db_module
from ..migrations import current_version

logger = logging.getLogger("migrate_sqlite_to_postgres")

#: Übertragungsreihenfolge: Eltern vor Kindern, damit die jetzt erzwungenen
#: Fremdschlüssel während des Laufs nie verletzt werden.
TABLE_ORDER: tuple[str, ...] = db_module.TABLES_IN_DEPENDENCY_ORDER

#: Spalten pro Tabelle, exakt so wie im PostgreSQL-Schema. Bewusst explizit
#: aufgeführt statt aus der Quelle abgeleitet: so fällt eine Abweichung
#: zwischen alter und neuer Struktur beim Lauf auf, statt still Daten zu
#: verlieren.
TABLE_COLUMNS: dict[str, tuple[str, ...]] = {
    "settings": ("key", "value"),
    "people": ("id", "name", "department", "active", "deleted"),
    "people_aliases": ("id", "person_id", "alias"),
    "week_plans": ("id", "kw", "start_date", "end_date", "source_pdf", "imported_at"),
    "assignments": (
        "id", "week_plan_id", "date", "category", "subcategory", "person_id", "raw_text",
    ),
    "absences": ("id", "week_plan_id", "date", "person_id", "typ"),
    "artist_plans": (
        "id", "start_date", "end_date", "source_filename", "sheet_name",
        "imported_at", "updated_at",
    ),
    "artist_plan_entries": ("id", "artist_plan_id", "date", "field_key", "content"),
    "rehearsal_plans": (
        "id", "start_date", "end_date", "source_filename", "imported_at", "updated_at",
    ),
    "rehearsals": (
        "id", "rehearsal_plan_id", "date", "start_time", "end_time", "location",
        "activity", "show_code", "participants_raw", "choreographer_raw", "end_inferred",
    ),
    "rehearsal_people": (
        "id", "rehearsal_id", "raw_name", "person_name", "role", "start_time", "end_time",
    ),
    "person_memory_overrides": (
        "id", "person_id", "facet", "item_key", "state", "value", "note", "updated_at",
    ),
    "employee_skills": (
        "id", "person_id", "skill_id", "name", "level", "source", "evidence_json",
        "created_at", "updated_at",
    ),
    "employee_memory": (
        "id", "person_id", "type", "subject", "value", "confidence", "source",
        "source_date", "editable", "note", "created_at", "updated_at",
    ),
    "employee_statistics": ("person_id", "data_version", "payload_json", "calculated_at"),
    "plan_audit_log": (
        "id", "week_plan_id", "start_date", "user_name", "event_type", "cause",
        "cell_key", "previous_value", "new_value", "metadata_json", "created_at",
    ),
    "recommendation_history": (
        "id", "week_plan_id", "start_date", "date", "category", "subcategory",
        "person_id", "score", "reasons_json", "accepted", "created_at",
    ),
}

#: Tabellen mit einer id-IDENTITY-Spalte, deren Sequenz nach dem Import
#: nachgezogen werden muss.
TABLES_WITH_IDENTITY: tuple[str, ...] = tuple(
    table for table, columns in TABLE_COLUMNS.items() if "id" in columns
)

#: Alle Fremdschlüsselbeziehungen als (Kindtabelle, Kindspalte, Elterntabelle,
#: Elternspalte). Basis für die Waisenprüfung VOR dem Schreiben und für den
#: Integritätsbericht danach.
FOREIGN_KEYS: tuple[tuple[str, str, str, str], ...] = (
    ("people_aliases", "person_id", "people", "id"),
    ("assignments", "week_plan_id", "week_plans", "id"),
    ("assignments", "person_id", "people", "id"),
    ("absences", "week_plan_id", "week_plans", "id"),
    ("absences", "person_id", "people", "id"),
    ("artist_plan_entries", "artist_plan_id", "artist_plans", "id"),
    ("rehearsals", "rehearsal_plan_id", "rehearsal_plans", "id"),
    ("rehearsal_people", "rehearsal_id", "rehearsals", "id"),
    ("person_memory_overrides", "person_id", "people", "id"),
    ("employee_skills", "person_id", "people", "id"),
    ("employee_memory", "person_id", "people", "id"),
    ("employee_statistics", "person_id", "people", "id"),
    ("plan_audit_log", "week_plan_id", "week_plans", "id"),
    ("recommendation_history", "week_plan_id", "week_plans", "id"),
    ("recommendation_history", "person_id", "people", "id"),
)

#: Batchgröße für executemany. Groß genug, um nicht zeilenweise zu arbeiten,
#: klein genug, um bei sehr großen Tabellen den Speicher nicht zu sprengen.
BATCH_SIZE = 500


class MigrationAborted(RuntimeError):
    """Der Lauf wurde bewusst abgebrochen - nichts wurde geschrieben."""


@dataclass
class CheckResult:
    name: str
    passed: bool
    detail: str = ""

    def line(self) -> str:
        return f"[{'PASS' if self.passed else 'FAIL'}] {self.name}{f' - {self.detail}' if self.detail else ''}"


@dataclass
class Report:
    checks: list[CheckResult] = field(default_factory=list)
    source_counts: dict[str, int] = field(default_factory=dict)
    target_counts: dict[str, int] = field(default_factory=dict)
    sequences: dict[str, int] = field(default_factory=dict)

    def add(self, name: str, passed: bool, detail: str = "") -> CheckResult:
        result = CheckResult(name, passed, detail)
        self.checks.append(result)
        return result

    @property
    def ok(self) -> bool:
        return all(check.passed for check in self.checks)


# ---------------------------------------------------------------------------
# Quelle (SQLite, strikt read-only)
# ---------------------------------------------------------------------------


def open_source(path: Path) -> sqlite3.Connection:
    """Öffnet die SQLite-Quelle read-only.

    `mode=ro` verhindert jede Schreiboperation auf Ebene der SQLite-Engine -
    das Skript kann die Ausgangsdatei also nicht verändern, auch nicht durch
    einen Programmierfehler. `sqlite3.connect()` würde eine fehlende Datei
    sonst stillschweigend als leere Datenbank neu anlegen; die URI-Form mit
    mode=ro schlägt stattdessen sauber fehl.
    """
    if not path.exists():
        raise MigrationAborted(f"SQLite-Quelldatei nicht gefunden: {path}")
    conn = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    return conn


def source_tables(conn: sqlite3.Connection) -> set[str]:
    return {
        row["name"]
        for row in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
        )
    }


def source_columns(conn: sqlite3.Connection, table: str) -> list[str]:
    return [row["name"] for row in conn.execute(f"PRAGMA table_info({table})")]


def count_rows_sqlite(conn: sqlite3.Connection, table: str) -> int:
    return conn.execute(f"SELECT COUNT(*) AS c FROM {table}").fetchone()["c"]


def find_orphans_sqlite(conn: sqlite3.Connection) -> list[tuple[str, str, str, int]]:
    """Findet Waisen in den Altdaten.

    Notwendig, weil SQLite die Fremdschlüssel nie erzwungen hat (PRAGMA
    foreign_keys wurde im Projekt nirgends gesetzt) - PostgreSQL tut es ab
    jetzt. Es wird nichts gelöscht und nichts repariert, nur berichtet.
    """
    orphans: list[tuple[str, str, str, int]] = []
    tables = source_tables(conn)
    for child, column, parent, parent_column in FOREIGN_KEYS:
        if child not in tables or parent not in tables:
            continue
        count = conn.execute(
            f"""SELECT COUNT(*) AS c FROM {child} c
                WHERE c.{column} IS NOT NULL
                  AND NOT EXISTS (
                      SELECT 1 FROM {parent} p WHERE p.{parent_column} = c.{column}
                  )"""
        ).fetchone()["c"]
        if count:
            orphans.append((child, column, parent, count))
    return orphans


# ---------------------------------------------------------------------------
# Ziel (PostgreSQL)
# ---------------------------------------------------------------------------


def count_rows_pg(conn, table: str) -> int:
    statement = pgsql.SQL("SELECT COUNT(*) AS c FROM {}").format(pgsql.Identifier(table))
    return conn.execute(statement).fetchone()["c"]


def target_is_empty(conn) -> tuple[bool, dict[str, int]]:
    counts = {table: count_rows_pg(conn, table) for table in TABLE_ORDER}
    return (sum(counts.values()) == 0), counts


def check_target_schema(conn) -> None:
    version = current_version(conn)
    if version is None:
        raise MigrationAborted(
            "Die Zieldatenbank hat noch kein Schema. Bitte zuerst die Migrationen "
            "anwenden: python -c \"from backend import db; db.initialize_database()\""
        )
    logger.info("Zielschema vorhanden (Migrationsstand %s).", version)


def copy_table(source: sqlite3.Connection, target, table: str) -> int:
    """Überträgt eine Tabelle vollständig, inklusive IDs und NULL-Werten."""
    columns = TABLE_COLUMNS[table]
    available = set(source_columns(source, table))
    missing = [column for column in columns if column not in available]
    if missing:
        raise MigrationAborted(
            f"Tabelle {table}: Spalten fehlen in der SQLite-Quelle: {', '.join(missing)}. "
            "Quelle und Zielschema passen nicht zusammen - Abbruch ohne Schreiben."
        )

    select = pgsql.SQL("")  # nur zur Klarheit: die Quelle ist SQLite, kein psycopg-SQL
    del select
    column_list = ", ".join(columns)
    cursor = source.execute(f"SELECT {column_list} FROM {table} ORDER BY rowid")

    insert = pgsql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
        pgsql.Identifier(table),
        pgsql.SQL(", ").join(pgsql.Identifier(column) for column in columns),
        pgsql.SQL(", ").join(pgsql.Placeholder() * len(columns)),
    )

    transferred = 0
    while True:
        batch = cursor.fetchmany(BATCH_SIZE)
        if not batch:
            break
        # tuple(row) erhält NULL-Werte als None und übernimmt die Typen
        # unverändert - INTEGER bleibt Ganzzahl, REAL bleibt Gleitkomma, TEXT
        # bleibt Text. Genau das will das Zielschema (siehe Migration 001).
        target.executemany(insert, [tuple(row) for row in batch])
        transferred += len(batch)
    return transferred


def fix_sequences(target) -> dict[str, int]:
    """Setzt jede IDENTITY-Sequenz auf MAX(id), damit der nächste Insert darüber liegt.

    Ohne diesen Schritt würde die Sequenz nach einem Import mit expliziten IDs
    weiter bei 1 stehen und der erste neue Datensatz sofort mit einem
    Primärschlüsselkonflikt scheitern.
    """
    results: dict[str, int] = {}
    for table in TABLES_WITH_IDENTITY:
        row = target.execute(
            pgsql.SQL(
                """SELECT setval(
                       pg_get_serial_sequence({table_literal}, 'id'),
                       COALESCE((SELECT MAX(id) FROM {table}), 1),
                       (SELECT MAX(id) IS NOT NULL FROM {table})
                   ) AS value"""
            ).format(
                table_literal=pgsql.Literal(table),
                table=pgsql.Identifier(table),
            )
        ).fetchone()
        results[table] = row["value"]
    return results


def find_orphans_pg(conn) -> list[tuple[str, str, str, int]]:
    orphans: list[tuple[str, str, str, int]] = []
    for child, column, parent, parent_column in FOREIGN_KEYS:
        statement = pgsql.SQL(
            """SELECT COUNT(*) AS c FROM {child} c
               WHERE c.{column} IS NOT NULL
                 AND NOT EXISTS (
                     SELECT 1 FROM {parent} p WHERE p.{parent_column} = c.{column}
                 )"""
        ).format(
            child=pgsql.Identifier(child),
            column=pgsql.Identifier(column),
            parent=pgsql.Identifier(parent),
            parent_column=pgsql.Identifier(parent_column),
        )
        count = conn.execute(statement).fetchone()["c"]
        if count:
            orphans.append((child, column, parent, count))
    return orphans


# ---------------------------------------------------------------------------
# Fachliche Stichproben
# ---------------------------------------------------------------------------


def business_samples(source: sqlite3.Connection, target, report: Report) -> None:
    """Vergleicht nicht nur Zeilenzahlen, sondern konkrete fachliche Ergebnisse.

    Eine reine COUNT-Prüfung würde eine vertauschte Spaltenzuordnung nicht
    bemerken. Deshalb hier gezielt die Zusammenhänge, an denen der Planner
    tatsächlich hängt: Aliasse einer Person, Zuweisungen einer Woche, Personen
    einer Probe, Abwesenheitseinträge.
    """
    tables = source_tables(source)

    # 1. Aliasse pro Person (Personenauflösung)
    if {"people", "people_aliases"} <= tables:
        row = source.execute(
            """SELECT p.id, p.name FROM people p
               JOIN people_aliases a ON a.person_id = p.id
               GROUP BY p.id ORDER BY COUNT(*) DESC, p.id LIMIT 1"""
        ).fetchone()
        if row is None:
            report.add("Stichprobe Aliase", True, "keine Aliase vorhanden")
        else:
            src = {
                r["alias"]
                for r in source.execute(
                    "SELECT alias FROM people_aliases WHERE person_id = ?", (row["id"],)
                )
            }
            dst = {
                r["alias"]
                for r in target.execute(
                    "SELECT alias FROM people_aliases WHERE person_id = %s", (row["id"],)
                ).fetchall()
            }
            report.add(
                f"Stichprobe Aliase (Mitarbeiter {row['name']!r})",
                src == dst,
                f"SQLite {len(src)} / PostgreSQL {len(dst)}",
            )

    # 2. Zuweisungen einer konkreten Kalenderwoche
    if {"week_plans", "assignments"} <= tables:
        row = source.execute(
            """SELECT w.id, w.start_date FROM week_plans w
               JOIN assignments a ON a.week_plan_id = w.id
               GROUP BY w.id ORDER BY COUNT(*) DESC, w.id LIMIT 1"""
        ).fetchone()
        if row is None:
            report.add("Stichprobe Zuweisungen", True, "keine Zuweisungen vorhanden")
        else:
            src = sorted(
                (r["date"], r["category"], r["subcategory"], r["person_id"])
                for r in source.execute(
                    """SELECT date, category, subcategory, person_id
                       FROM assignments WHERE week_plan_id = ?""",
                    (row["id"],),
                )
            )
            dst = sorted(
                (r["date"], r["category"], r["subcategory"], r["person_id"])
                for r in target.execute(
                    """SELECT date, category, subcategory, person_id
                       FROM assignments WHERE week_plan_id = %s""",
                    (row["id"],),
                ).fetchall()
            )
            report.add(
                f"Stichprobe Zuweisungen (KW ab {row['start_date']})",
                src == dst,
                f"{len(src)} Zeilen",
            )

    # 3. Personen einer Probe
    if {"rehearsals", "rehearsal_people"} <= tables:
        row = source.execute(
            """SELECT r.id, r.activity FROM rehearsals r
               JOIN rehearsal_people rp ON rp.rehearsal_id = r.id
               GROUP BY r.id ORDER BY COUNT(*) DESC, r.id LIMIT 1"""
        ).fetchone()
        if row is None:
            report.add("Stichprobe Probenteilnehmer", True, "keine Proben vorhanden")
        else:
            src = sorted(
                (r["raw_name"], r["person_name"], r["role"])
                for r in source.execute(
                    "SELECT raw_name, person_name, role FROM rehearsal_people WHERE rehearsal_id = ?",
                    (row["id"],),
                )
            )
            dst = sorted(
                (r["raw_name"], r["person_name"], r["role"])
                for r in target.execute(
                    "SELECT raw_name, person_name, role FROM rehearsal_people WHERE rehearsal_id = %s",
                    (row["id"],),
                ).fetchall()
            )
            report.add(
                f"Stichprobe Probenteilnehmer ({row['activity']!r})",
                src == dst,
                f"{len(src)} Personen",
            )

    # 4. Abwesenheiten (Urlaub/Frei/krank)
    if "absences" in tables:
        src = sorted(
            (r["date"], r["person_id"], r["typ"])
            for r in source.execute("SELECT date, person_id, typ FROM absences")
        )
        dst = sorted(
            (r["date"], r["person_id"], r["typ"])
            for r in target.execute("SELECT date, person_id, typ FROM absences").fetchall()
        )
        report.add("Stichprobe Abwesenheiten", src == dst, f"{len(src)} Einträge")

    # 5. Manuelle Gedächtnis-Korrekturen (dürfen unter keinen Umständen verloren gehen)
    if "person_memory_overrides" in tables:
        src = sorted(
            (r["person_id"], r["facet"], r["item_key"], r["state"])
            for r in source.execute(
                "SELECT person_id, facet, item_key, state FROM person_memory_overrides"
            )
        )
        dst = sorted(
            (r["person_id"], r["facet"], r["item_key"], r["state"])
            for r in target.execute(
                "SELECT person_id, facet, item_key, state FROM person_memory_overrides"
            ).fetchall()
        )
        report.add("Stichprobe Gedächtnis-Overrides", src == dst, f"{len(src)} Einträge")


# ---------------------------------------------------------------------------
# Abläufe
# ---------------------------------------------------------------------------


def run_dry_run(source_path: Path) -> Report:
    """Prüft alles, schreibt nichts (Sprint-Punkt 23)."""
    report = Report()
    source = open_source(source_path)
    target = db_module.connect_direct()
    try:
        report.add("Quelle erreichbar", True, str(source_path))
        report.add("Ziel erreichbar", True, "über DATABASE_URL")

        version = current_version(target)
        report.add(
            "Zielschema vorhanden",
            version is not None,
            f"Migrationsstand {version}" if version else
            "keine Migration angewendet - zuerst db.initialize_database() ausführen",
        )

        tables = source_tables(source)
        missing = [table for table in TABLE_ORDER if table not in tables]
        report.add(
            "Alle erwarteten Tabellen in der Quelle",
            not missing,
            f"fehlen: {', '.join(missing)}" if missing else f"{len(TABLE_ORDER)}/{len(TABLE_ORDER)}",
        )

        for table in TABLE_ORDER:
            report.source_counts[table] = count_rows_sqlite(source, table) if table in tables else 0

        # Alles Weitere setzt ein vorhandenes Zielschema voraus. Ohne das
        # würde die erste fehlschlagende Abfrage die Transaktion abbrechen und
        # jede folgende Prüfung mit einem Folgefehler übertönen - der Bericht
        # bliebe dann bei "relation does not exist" statt die eigentliche
        # Ursache zu nennen.
        if version is None:
            return report

        for table in TABLE_ORDER:
            report.target_counts[table] = count_rows_pg(target, table)

        empty, counts = target_is_empty(target)
        report.add(
            "Ziel ist leer",
            empty,
            "leer" if empty else
            "belegt: " + ", ".join(f"{t}={c}" for t, c in counts.items() if c),
        )

        orphans = find_orphans_sqlite(source)
        report.add(
            "Keine Waisen in den Altdaten",
            not orphans,
            "; ".join(f"{c}.{col} -> {p}: {n}" for c, col, p, n in orphans) if orphans else
            f"{len(FOREIGN_KEYS)} Beziehungen geprüft",
        )
    finally:
        source.close()
        target.close()
    return report


def run_migration(source_path: Path, *, allow_non_empty: bool) -> Report:
    report = Report()
    source = open_source(source_path)
    target = db_module.connect_direct()
    try:
        check_target_schema(target)

        tables = source_tables(source)
        missing = [table for table in TABLE_ORDER if table not in tables]
        if missing:
            raise MigrationAborted(
                "In der SQLite-Quelle fehlen Tabellen: " + ", ".join(missing)
            )

        orphans = find_orphans_sqlite(source)
        if orphans:
            details = "\n".join(
                f"  - {child}.{column} verweist auf nicht vorhandene {parent}: {count} Zeilen"
                for child, column, parent, count in orphans
            )
            raise MigrationAborted(
                "Die Altdaten enthalten verwaiste Verweise. PostgreSQL erzwingt die "
                "Fremdschlüssel, die SQLite nie geprüft hat - die Migration würde "
                "scheitern.\n" + details + "\n"
                "Es wurde NICHTS gelöscht und NICHTS geschrieben. Bitte fachlich "
                "entscheiden, wie mit diesen Zeilen umgegangen wird."
            )

        empty, counts = target_is_empty(target)
        if not empty:
            if not allow_non_empty:
                belegt = ", ".join(f"{t}={c}" for t, c in counts.items() if c)
                raise MigrationAborted(
                    f"Die Zieldatenbank ist nicht leer ({belegt}). Abbruch, es wurde "
                    "nichts geschrieben. Wenn der vorhandene Inhalt bewusst ersetzt "
                    "werden soll: --allow-non-empty."
                )
            logger.warning(
                "--allow-non-empty: die folgenden vorhandenen Datensätze werden GELÖSCHT: %s",
                ", ".join(f"{t}={c}" for t, c in counts.items() if c),
            )

        for table in TABLE_ORDER:
            report.source_counts[table] = count_rows_sqlite(source, table)

        # Ab hier eine einzige Transaktion: entweder alles oder nichts.
        try:
            if not empty:
                db_module.truncate_all_tables(target)
            for table in TABLE_ORDER:
                transferred = copy_table(source, target, table)
                logger.info("%-26s %6d Zeilen", table, transferred)
            report.sequences = fix_sequences(target)
            target.commit()
        except Exception as exc:  # noqa: BLE001 - wird sofort neu geworfen
            target.rollback()
            raise MigrationAborted(
                f"Migration fehlgeschlagen und vollständig zurückgerollt: {exc}"
            ) from exc

        # --- Verifikation (Sprint-Punkte 24/25) ---
        for table in TABLE_ORDER:
            report.target_counts[table] = count_rows_pg(target, table)
            report.add(
                f"Zeilenzahl {table}",
                report.source_counts[table] == report.target_counts[table],
                f"SQLite {report.source_counts[table]} / PostgreSQL {report.target_counts[table]}",
            )

        business_samples(source, target, report)

        remaining = find_orphans_pg(target)
        report.add(
            "Referenzielle Integrität im Ziel",
            not remaining,
            "; ".join(f"{c}.{col} -> {p}: {n}" for c, col, p, n in remaining) if remaining else
            f"{len(FOREIGN_KEYS)} Beziehungen geprüft",
        )

        for table, value in report.sequences.items():
            max_row = target.execute(
                pgsql.SQL("SELECT COALESCE(MAX(id), 0) AS m FROM {}").format(
                    pgsql.Identifier(table)
                )
            ).fetchone()
            report.add(
                f"Sequenz {table}",
                value >= max_row["m"],
                f"setval={value}, MAX(id)={max_row['m']}",
            )
    finally:
        source.close()
        target.close()
    return report


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _print_report(report: Report, *, dry_run: bool) -> None:
    print()
    print("=" * 72)
    print("DRY RUN - es wurde nichts geschrieben" if dry_run else "MIGRATIONSBERICHT")
    print("=" * 72)

    if report.source_counts:
        print()
        print(f"{'Tabelle':<28}{'SQLite':>10}{'PostgreSQL':>14}")
        print("-" * 52)
        for table in TABLE_ORDER:
            src = report.source_counts.get(table, 0)
            dst = report.target_counts.get(table, 0)
            print(f"{table:<28}{src:>10}{dst:>14}")

    if report.sequences:
        print()
        print("Sequenzen nach dem Import:")
        for table, value in report.sequences.items():
            print(f"  {table:<28} -> {value}")

    print()
    for check in report.checks:
        print(check.line())
    print()
    print("ERGEBNIS:", "PASS" if report.ok else "FAIL")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="migrate_sqlite_to_postgres",
        description=(
            "Überträgt eine Planner-SQLite-Datenbank nach PostgreSQL. Das Ziel wird "
            "ausschließlich über die Umgebungsvariable DATABASE_URL bestimmt."
        ),
    )
    parser.add_argument(
        "--source",
        type=Path,
        required=True,
        help="Pfad zur SQLite-Quelldatei (wird ausschließlich lesend geöffnet).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Nur prüfen (Erreichbarkeit, Schema, Zeilenzahlen, Konflikte, Waisen).",
    )
    parser.add_argument(
        "--allow-non-empty",
        action="store_true",
        help=(
            "Erlaubt die Migration in eine bereits gefüllte Zieldatenbank. "
            "Vorhandene Daten werden dabei GELÖSCHT. Ohne diese Option bricht das "
            "Skript bei einem nicht leeren Ziel ab."
        ),
    )
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    if not os.getenv("DATABASE_URL"):
        print(
            "DATABASE_URL ist nicht gesetzt. Das Ziel wird bewusst nur über die "
            "Umgebung konfiguriert, damit keine Zugangsdaten in der Prozessliste "
            "oder der Shell-History landen.",
            file=sys.stderr,
        )
        return 2

    try:
        if args.dry_run:
            report = run_dry_run(args.source)
        else:
            report = run_migration(args.source, allow_non_empty=args.allow_non_empty)
    except MigrationAborted as exc:
        print(f"\nABBRUCH: {exc}", file=sys.stderr)
        return 1
    except (psycopg.Error, sqlite3.Error) as exc:
        print(f"\nDatenbankfehler: {exc}", file=sys.stderr)
        return 1

    _print_report(report, dry_run=args.dry_run)
    return 0 if report.ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
