"""Tests für backend/db.py - immer gegen ein isoliertes PostgreSQL-Testschema,
niemals gegen eine echte Planungsdatenbank (siehe conftest.py)."""
from __future__ import annotations

from backend import db as db_module
from backend import migrations as migrations_module

#: Alle 17 Fachtabellen des Schemas. Die frühere Fassung prüfte nur eine
#: Teilmenge; nach der Migration wird bewusst das vollständige Schema geprüft,
#: weil es jetzt aus einer versionierten Datei stammt und nicht mehr aus
#: verstreuten CREATE-TABLE-IF-NOT-EXISTS-Anweisungen.
EXPECTED_TABLES = set(db_module.TABLES_IN_DEPENDENCY_ORDER)


def _table_names(conn) -> set[str]:
    """Alle Tabellen im aktuellen (isolierten) Testschema."""
    rows = conn.execute(
        """SELECT table_name
           FROM information_schema.tables
           WHERE table_schema = current_schema()
             AND table_type = 'BASE TABLE'"""
    ).fetchall()
    return {row["table_name"] for row in rows}


def test_initialize_database_creates_expected_tables(test_conn):
    assert EXPECTED_TABLES.issubset(_table_names(test_conn))


def test_schema_migrations_table_records_the_applied_version(test_conn):
    """Ersetzt den früheren `PRAGMA integrity_check`-Test.

    PostgreSQL hat kein Äquivalent dazu (siehe
    docs/database/POSTGRES_MIGRATION_AUDIT.md). Was hier stattdessen
    nachgewiesen werden kann und muss: das Schema stammt aus einer
    nachvollziehbaren, versionierten Migration und ist vollständig angewendet.
    """
    version = migrations_module.current_version(test_conn)
    assert version == "001"
    assert migrations_module.pending_migrations(test_conn) == []


def test_initialize_database_is_idempotent(test_conn):
    """Ein zweiter Lauf darf weder fehlschlagen noch erneut migrieren."""
    before = _table_names(test_conn)
    db_module.initialize_database()
    assert _table_names(test_conn) == before
    assert migrations_module.pending_migrations(test_conn) == []


def test_reading_people_works_on_a_fresh_database(test_conn):
    person_id = db_module.create_person(test_conn, "Test-MA", "Testabteilung")
    people = db_module.get_all_people(test_conn)
    names = [p["name"] for p in people]

    assert person_id > 0
    assert "Test-MA" in names


def test_identity_sequence_continues_after_explicit_ids(test_conn):
    """Sprint-Punkt 9: nach übernommenen IDs muss der nächste INSERT > MAX(id) sein.

    Die IDENTITY-Spalten sind GENERATED BY DEFAULT, damit das Migrationstool
    bestehende SQLite-IDs setzen kann. Genau dann muss die Sequenz danach
    nachgezogen werden - sonst kollidiert der erste neue Datensatz.
    """
    test_conn.execute(
        "INSERT INTO people (id, name, active, deleted) VALUES (100, 'Explizit', 1, 0)"
    )
    test_conn.execute(
        "SELECT setval(pg_get_serial_sequence('people', 'id'), "
        "(SELECT MAX(id) FROM people))"
    )
    new_id = db_module.create_person(test_conn, "Danach")
    assert new_id > 100
