-- 001_initial_postgres
--
-- Vollständiges Ausgangsschema des Planner-Agenten auf PostgreSQL.
-- Fachlich 1:1 aus dem bisherigen SQLite-Schema (backend/db.py::SCHEMA vor der
-- Migration) übernommen - siehe docs/database/POSTGRES_MIGRATION_AUDIT.md für die
-- vollständige Gegenüberstellung. Bewusst NICHT mitgeändert wurden Feldnamen,
-- Wertebereiche, Rollen-/Statuswerte oder Datumsformate.
--
-- Zwei Entscheidungen, die hier bewusst gegen den "modernen" Default getroffen sind:
--
--   1. Datums-/Zeitspalten bleiben TEXT (ISO 'YYYY-MM-DD' bzw. 'HH:MM'). Der gesamte
--      Fachcode vergleicht, sortiert und serialisiert diese Werte als Strings
--      (BETWEEN, date.fromisoformat, JSON-Response). Ein Wechsel auf date/time würde
--      die API-Antworten verändern - der Sprint verlangt ausdrücklich unveränderte
--      API-Verträge.
--
--   2. Boolesche Flags bleiben INTEGER (0/1). Der Code schreibt 1/0 und liest
--      bool(...). Ein echtes boolean würde in dict(row)-basierten Responses aus 1
--      plötzlich true machen - wieder eine API-Änderung.
--
-- IDs sind IDENTITY-Spalten mit BY DEFAULT (nicht ALWAYS), damit das Migrationstool
-- bestehende SQLite-IDs explizit übernehmen kann; die Sequenzen werden danach auf
-- MAX(id) nachgezogen (siehe backend/scripts/migrate_sqlite_to_postgres.py).

-- ---------------------------------------------------------------------------
-- Case-insensitive Faltung, exakt wie SQLites COLLATE NOCASE
-- ---------------------------------------------------------------------------
-- SQLites eingebaute NOCASE-Kollation faltet laut eigener Dokumentation NUR
-- ASCII A-Z. PostgreSQLs lower() faltet dagegen volles Unicode ('RENÉ' -> 'rené').
-- Ein naives lower() würde die Personenauflösung damit WEITER machen als bisher -
-- eine stille Semantikänderung an der zentralen Alias-/Namensauflösung.
--
-- planner_nocase() bildet deshalb exakt dieselbe Abbildung ab wie
-- db._nocase_fold() in Python (das den Unterschied bereits seit AP5a dokumentiert).
-- translate() ist IMMUTABLE und damit für funktionale Indizes verwendbar.
CREATE OR REPLACE FUNCTION planner_nocase(value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
RETURNS NULL ON NULL INPUT
AS $$
    SELECT translate(value, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')
$$;

-- SQLite liefert CURRENT_TIMESTAMP als String 'YYYY-MM-DD HH:MM:SS' in UTC und
-- genau dieser String landet unverändert in JSON-Antworten (created_at/updated_at).
-- Diese Funktion erhält das Format; ein timestamptz-Default würde das
-- Antwortformat verändern.
CREATE OR REPLACE FUNCTION planner_now_text()
RETURNS text
LANGUAGE sql
STABLE
AS $$
    SELECT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
$$;

-- ---------------------------------------------------------------------------
-- Stammdaten
-- ---------------------------------------------------------------------------

CREATE TABLE people (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    department TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    deleted INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE people_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
    alias TEXT NOT NULL UNIQUE
);

CREATE TABLE settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- ---------------------------------------------------------------------------
-- Dienstpläne
-- ---------------------------------------------------------------------------

CREATE TABLE week_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kw INTEGER,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    source_pdf TEXT,
    imported_at TEXT DEFAULT planner_now_text()
);

-- ON DELETE CASCADE entspricht exakt dem heutigen Verhalten von
-- db.delete_week_plan(): dort werden assignments und absences vor der Woche
-- manuell gelöscht. person_id bleibt RESTRICT, weil Personen nie hart gelöscht
-- werden (db.delete_person macht einen Soft-Delete: active=0, deleted=1).
CREATE TABLE assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_plan_id BIGINT NOT NULL REFERENCES week_plans(id) ON DELETE CASCADE,
    date TEXT NOT NULL,
    category TEXT NOT NULL,
    subcategory TEXT,
    person_id BIGINT REFERENCES people(id) ON DELETE RESTRICT,
    raw_text TEXT
);

CREATE TABLE absences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_plan_id BIGINT NOT NULL REFERENCES week_plans(id) ON DELETE CASCADE,
    date TEXT NOT NULL,
    person_id BIGINT REFERENCES people(id) ON DELETE RESTRICT,
    typ TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- Künstlerplan
-- ---------------------------------------------------------------------------

CREATE TABLE artist_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TEXT NOT NULL UNIQUE,
    end_date TEXT NOT NULL,
    source_filename TEXT,
    sheet_name TEXT,
    imported_at TEXT DEFAULT planner_now_text(),
    updated_at TEXT DEFAULT planner_now_text()
);

CREATE TABLE artist_plan_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist_plan_id BIGINT NOT NULL REFERENCES artist_plans(id) ON DELETE CASCADE,
    date TEXT NOT NULL,
    field_key TEXT NOT NULL,
    content TEXT,
    UNIQUE (artist_plan_id, date, field_key)
);

-- ---------------------------------------------------------------------------
-- Probenplan
-- ---------------------------------------------------------------------------

CREATE TABLE rehearsal_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TEXT NOT NULL UNIQUE,
    end_date TEXT NOT NULL,
    source_filename TEXT,
    imported_at TEXT DEFAULT planner_now_text(),
    updated_at TEXT DEFAULT planner_now_text()
);

CREATE TABLE rehearsals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rehearsal_plan_id BIGINT NOT NULL REFERENCES rehearsal_plans(id) ON DELETE CASCADE,
    date TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    location TEXT,
    activity TEXT NOT NULL,
    show_code TEXT,
    participants_raw TEXT,
    choreographer_raw TEXT,
    end_inferred INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE rehearsal_people (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rehearsal_id BIGINT NOT NULL REFERENCES rehearsals(id) ON DELETE CASCADE,
    raw_name TEXT NOT NULL,
    person_name TEXT,
    role TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- Mitarbeitergedächtnis
-- ---------------------------------------------------------------------------

-- Tobis Korrekturen am MA-Gedächtnis. Bewusst getrennt von allen abgeleiteten Daten:
-- das Gedächtnis wird bei jedem Lesen neu gerechnet, nur diese Tabelle wird gespeichert.
-- Dadurch überlebt eine Korrektur auch das Neu-Aufbauen der Probenplan-Tabellen beim
-- Re-Import. Schlüssel ist person_id (nie ein Name), damit Umbenennen/Soft-Delete nichts
-- verliert.
CREATE TABLE person_memory_overrides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
    facet TEXT NOT NULL,        -- 'show' | 'free' | 'task'
    item_key TEXT NOT NULL,     -- show: Show-Code | free: 'weekdays' | task: normalisierte Kategorie
    state TEXT NOT NULL,        -- 'confirmed' | 'removed' | 'added' | 'pinned'
    value TEXT,                 -- JSON, nur für 'pinned' bzw. Zusatzinfos
    note TEXT,
    updated_at TEXT NOT NULL DEFAULT planner_now_text(),
    UNIQUE (person_id, facet, item_key)
);

-- Sprint 5: Manuell gepflegte, strukturierte Fähigkeiten. Automatisch erkannte
-- Vorschläge werden weiterhin reproduzierbar aus der Historie berechnet.
CREATE TABLE employee_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
    skill_id TEXT NOT NULL,
    name TEXT NOT NULL,
    level INTEGER NOT NULL CHECK (level BETWEEN 1 AND 5),
    source TEXT NOT NULL DEFAULT 'manual',
    evidence_json TEXT,
    created_at TEXT NOT NULL DEFAULT planner_now_text(),
    updated_at TEXT NOT NULL DEFAULT planner_now_text(),
    UNIQUE (person_id, skill_id)
);

-- Freie, aber strukturierte Hinweise: kein Chat-Text, sondern Typ + Betreff +
-- Wert mit Quelle, Datum und Konfidenz. Historisch abgeleitete Einträge werden
-- nicht festgeschrieben, sondern bei jedem Lesen nachvollziehbar neu erzeugt.
CREATE TABLE employee_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    subject TEXT NOT NULL,
    value TEXT NOT NULL,
    confidence DOUBLE PRECISION NOT NULL DEFAULT 1.0 CHECK (confidence BETWEEN 0 AND 1),
    source TEXT NOT NULL DEFAULT 'manual',
    source_date TEXT NOT NULL,
    editable INTEGER NOT NULL DEFAULT 1,
    note TEXT,
    created_at TEXT NOT NULL DEFAULT planner_now_text(),
    updated_at TEXT NOT NULL DEFAULT planner_now_text(),
    UNIQUE (person_id, type, subject, source)
);

-- Materialisierter Cache. data_version ist ein Fingerabdruck der unveränderten
-- historischen Quelltabellen; bei jeder relevanten Änderung wird neu gerechnet.
CREATE TABLE employee_statistics (
    person_id BIGINT PRIMARY KEY REFERENCES people(id) ON DELETE CASCADE,
    data_version TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    calculated_at TEXT NOT NULL DEFAULT planner_now_text()
);

-- ---------------------------------------------------------------------------
-- Audit / Empfehlungen
-- ---------------------------------------------------------------------------

-- ON DELETE SET NULL statt CASCADE: heute (SQLite ohne erzwungene Fremdschlüssel)
-- bleibt ein Auditeintrag beim Löschen seiner Woche schlicht stehen. CASCADE würde
-- Audithistorie vernichten, RESTRICT würde DELETE FROM week_plans neu fehlschlagen
-- lassen. SET NULL erhält den Eintrag - die Spalte ist bereits nullable und
-- intelligence/audit.list_events() kann auch rein über start_date filtern.
CREATE TABLE plan_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_plan_id BIGINT REFERENCES week_plans(id) ON DELETE SET NULL,
    start_date TEXT NOT NULL,
    user_name TEXT NOT NULL DEFAULT 'Planer',
    event_type TEXT NOT NULL,
    cause TEXT NOT NULL,
    cell_key TEXT,
    previous_value TEXT,
    new_value TEXT,
    metadata_json TEXT,
    created_at TEXT NOT NULL DEFAULT planner_now_text()
);

CREATE TABLE recommendation_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_plan_id BIGINT REFERENCES week_plans(id) ON DELETE SET NULL,
    start_date TEXT NOT NULL,
    date TEXT,
    category TEXT,
    subcategory TEXT,
    person_id BIGINT REFERENCES people(id) ON DELETE RESTRICT,
    score DOUBLE PRECISION,
    reasons_json TEXT,
    accepted INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT planner_now_text()
);

-- ---------------------------------------------------------------------------
-- Indizes (1:1 aus dem SQLite-Schema, NOCASE -> funktionaler planner_nocase-Index)
-- ---------------------------------------------------------------------------

CREATE INDEX idx_assignments_person_date ON assignments (person_id, date);
CREATE INDEX idx_absences_person_date ON absences (person_id, date);
CREATE INDEX idx_audit_week_created ON plan_audit_log (week_plan_id, created_at DESC);

-- people.name und people_aliases.alias tragen bereits case-SENSITIVE UNIQUE-Indizes.
-- find_person_by_alias() sucht case-INSENSITIV; dafür braucht es einen eigenen
-- funktionalen Index, damit daraus kein Seq Scan wird (SQLite hatte dafür die
-- COLLATE-NOCASE-Indizes). Die case-sensitive UNIQUE-Prüfung bleibt unangetastet.
CREATE INDEX idx_people_aliases_alias_nocase ON people_aliases (planner_nocase(alias));
CREATE INDEX idx_people_name_nocase ON people (planner_nocase(name));

-- assignments/absences werden an mehreren Stellen ausschließlich nach week_plan_id
-- gefiltert (get_assignments_for_week, get_absences_for_week, delete_week_plan,
-- die Zähl-Subqueries in get_week_plans).
CREATE INDEX idx_assignments_week_plan_id ON assignments (week_plan_id);
CREATE INDEX idx_absences_week_plan_id ON absences (week_plan_id);

-- rehearsals wird sowohl nach date (get_rehearsal_events, get_rehearsal_intervals
-- über einen JOIN) als auch nach rehearsal_plan_id gefiltert.
CREATE INDEX idx_rehearsals_date ON rehearsals (date);
CREATE INDEX idx_rehearsals_rehearsal_plan_id ON rehearsals (rehearsal_plan_id);

-- rehearsal_people wird über rehearsal_id nachgeladen (get_rehearsals) bzw. beim
-- Neuaufbau eines Probenplans gelöscht (upsert_rehearsal_plan).
CREATE INDEX idx_rehearsal_people_rehearsal_id ON rehearsal_people (rehearsal_id);

-- plan_audit_log wird von intelligence/audit.list_events() auch rein nach
-- start_date gefiltert - idx_audit_week_created deckt das nicht ab (führende
-- Spalte week_plan_id).
CREATE INDEX idx_plan_audit_log_start_date ON plan_audit_log (start_date);

-- Zusätzlich gegenüber SQLite: die case-insensitive Show-Teilnahme-Abfrage in
-- intelligence/employee_stats._current_week_statistics() filtert über
-- planner_nocase(person_name)/planner_nocase(raw_name). Unter SQLite lief das
-- ohne Index (voller SCAN); PostgreSQL bekommt hier die passenden Indizes.
CREATE INDEX idx_rehearsal_people_person_name_nocase
    ON rehearsal_people (planner_nocase(person_name));
CREATE INDEX idx_rehearsal_people_raw_name_nocase
    ON rehearsal_people (planner_nocase(raw_name));
